from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import nbformat
import numpy as np
import pytest


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RUNNER_PATH = PROJECT_ROOT / "chapter_5_options_strategies/src/run_chapter5_analysis.py"


@pytest.fixture(scope="module")
def chapter5():
    spec = importlib.util.spec_from_file_location("chapter5_test_module", RUNNER_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def data(chapter5):
    return chapter5.load_data()


@pytest.fixture(scope="module")
def results(chapter5, data):
    return chapter5.run_experiments(data)


def test_official_archive_contract(chapter5, data):
    chapter5.validate_offline_assets()
    manifest = json.loads(chapter5.MANIFEST_PATH.read_text(encoding="utf-8"))
    assert len(manifest["members"]) == 40
    assert sum(row["kind"] == "original_source" for row in manifest["members"]) == 30
    assert sum(row["kind"] == "research_data" for row in manifest["members"]) == 10
    assert len(data.etf_dates) == 2500
    assert len(data.vx_dates) == 2877
    assert data.etf_stocks[data.etf_stocks.index("SPY")] == "SPY"
    assert data.vx_contracts[data.vx_contracts.index("0000$")] == "0000$"


def test_volatility_direction_exact_replay(chapter5, results):
    actual = results["volatility_direction"]["values"]
    for key, expected in chapter5.SOURCE_VOL_DIRECTION.items():
        assert actual[key] == pytest.approx(expected, abs=chapter5.STRICT_TOLERANCE)
    assert results["volatility_direction"]["counts"]["all"] == {
        "same_direction": 876,
        "denominator": 2498,
    }


def test_xiv_spy_roll_exact_replay(chapter5, results):
    replay = results["xiv_roll"]
    assert replay["dates"][0] == 20101130
    assert replay["dates"][-1] == 20150819
    assert len(replay["returns"]) == 1188
    for key, expected in chapter5.SOURCE_XIV_ROLL.items():
        assert replay["performance"][key] == pytest.approx(
            expected, abs=chapter5.STRICT_TOLERANCE
        )
    assert replay["contract"]["signal_uses_previous_day_vx_and_vix"] is True
    assert replay["contract"]["positions_applied_one_day_later"] is True


def test_black_scholes_independent_invariants(results):
    theory = results["option_theory"]
    assert abs(theory["parity_error"]) < 1e-10
    assert abs(theory["delta_finite_difference_error"]) < 1e-7
    assert abs(theory["gamma_finite_difference_error"]) < 1e-6
    assert theory["recovered_sigma"] == pytest.approx(
        theory["inputs"]["sigma"], abs=1e-10
    )
    assert np.all(np.isfinite(theory["call_leverage"]))
    assert np.all(np.isfinite(theory["put_leverage"]))


def test_gamma_scalping_path_and_cost_contract(results):
    gamma = results["gamma_scalping"]
    assert gamma["same_start"] is True
    assert gamma["same_end"] is True
    assert gamma["is_illustration_not_backtest"] is True
    assert gamma["pnl"]["quiet"]["0.0"] != gamma["pnl"]["oscillating"]["0.0"]
    for path in ("quiet", "oscillating"):
        assert (
            gamma["pnl"][path]["5.0"]
            <= gamma["pnl"][path]["1.0"]
            <= gamma["pnl"][path]["0.0"]
        )


def test_noncomparable_results_are_machine_readable(chapter5, results):
    assert results["forecast_overlap"]["compared"] is False
    assert "20150828" in results["forecast_overlap"]["reason"]
    references = chapter5.reference_only_results()
    assert len(references) == 6
    assert all(row["compared"] is False for row in references)
    assert all(row["reason"] and row["book_output"] for row in references)
    assert "combines" in references[0]["reason"]
    assert sum("licensed" in row["reason"] for row in references) >= 2


def test_all_chapter5_verifications_pass(chapter5, data, results):
    checks = chapter5.verify_results(data, results)
    assert len(checks) == 22
    assert all(checks.values())
    comparisons = chapter5.source_comparisons(results)
    assert len(comparisons) == 7
    assert all(row["matches_source"] for row in comparisons)


def test_generated_metrics_use_strict_booleans(chapter5):
    metrics_path = chapter5.REPORT_DIR / "metrics.json"
    if not metrics_path.exists():
        pytest.skip("metrics are generated by the chapter entrypoint")
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    assert all(type(value) is bool for value in metrics["verification"]["checks"].values())
    assert all(
        type(row["compared"]) is bool and row["compared"] is False
        for row in metrics["reference_only_comparisons"]
    )


def test_generated_notebook_is_fully_executed(chapter5):
    if not chapter5.NOTEBOOK_PATH.exists():
        pytest.skip("notebook is generated by the chapter entrypoint")
    notebook = nbformat.read(chapter5.NOTEBOOK_PATH, as_version=4)
    code = [cell for cell in notebook.cells if cell.cell_type == "code"]
    assert code and all(cell.execution_count is not None for cell in code)
    assert not any(
        output.output_type == "error" for cell in code for output in cell.outputs
    )
    png_count = sum(
        "image/png" in output.get("data", {})
        for cell in code
        for output in cell.outputs
    )
    assert png_count == 5


def test_generated_markdown_math_is_clean(chapter5):
    report = chapter5.REPORT_DIR / "chapter5_report.md"
    if not report.exists():
        pytest.skip("report is generated by the chapter entrypoint")
    chapter5.assert_clean_markdown_math(report.read_text(encoding="utf-8"), "report")
    notebook = nbformat.read(chapter5.NOTEBOOK_PATH, as_version=4)
    for index, cell in enumerate(notebook.cells):
        if cell.cell_type == "markdown":
            chapter5.assert_clean_markdown_math(cell.source, f"notebook cell {index}")
